// Android backend: JNI bridge to usb-serial-for-android, loaded from an embedded
// classes.dex. Only meaningful under __ANDROID__; guarded so it compiles as a stub
// elsewhere (though CMake only builds it on Android).

#include "AndroidBackend.hpp"

#ifdef __ANDROID__
#  include <jni.h>
#  include <android/log.h>
#  include <sys/stat.h>
#  include <sys/types.h>
#  include <cstdio>
#  include <cstring>
#  include <fstream>
#  include <unordered_map>
#  include <vector>
#endif

namespace cps {
namespace detail {

#ifdef __ANDROID__

// Embedded dex bytes, generated by cmake/cps_dex.cmake into cps_classes_dex.cpp.
extern "C" const unsigned char cps_classes_dex[];
extern "C" const unsigned long cps_classes_dex_len;

#define CPS_LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "cps", __VA_ARGS__)
#define CPS_LOGI(...) __android_log_print(ANDROID_LOG_INFO,  "cps", __VA_ARGS__)

namespace {

struct JniThread {
    JNIEnv* env = nullptr;
    bool attached = false;
    bool ok = false;
    explicit JniThread(JavaVM* vm) {
        if (!vm) return;
        if (vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6) == JNI_OK) {
            ok = true;
            return;
        }
        JavaVMAttachArgs args{JNI_VERSION_1_6, "cps", nullptr};
        if (vm->AttachCurrentThread(&env, &args) == JNI_OK) {
            attached = true;
            ok = true;
        }
    }
    ~JniThread() {
        // detach handled by global VM pointer when needed
    }
};

// ---- global JNI state ----
JavaVM*  g_vm = nullptr;
jobject  g_context = nullptr;     // global ref
jclass   g_bridgeClass = nullptr; // global ref

jmethodID g_midEnumerate = nullptr;
jmethodID g_midOpen      = nullptr;
jmethodID g_midWrite     = nullptr;
jmethodID g_midClose     = nullptr;

std::mutex g_registryMx;
std::unordered_map<std::int64_t, AndroidBackend*>& registry() {
    static std::unordered_map<std::int64_t, AndroidBackend*> r;
    return r;
}

void registerInstance(std::int64_t id, AndroidBackend* b) {
    std::lock_guard<std::mutex> lk(g_registryMx);
    registry()[id] = b;
}
void unregisterInstance(std::int64_t id) {
    std::lock_guard<std::mutex> lk(g_registryMx);
    registry().erase(id);
}
AndroidBackend* findInstance(std::int64_t id) {
    std::lock_guard<std::mutex> lk(g_registryMx);
    auto it = registry().find(id);
    return it == registry().end() ? nullptr : it->second;
}

bool ensureDir(const std::string& path) {
    for (std::size_t i = 1; i < path.size(); ++i) {
        if (path[i] == '/') {
            std::string sub = path.substr(0, i);
            ::mkdir(sub.c_str(), 0700);
        }
    }
    ::mkdir(path.c_str(), 0700);
    return true;
}

// Native callbacks invoked by the Java bridge (registered via RegisterNatives).
JNIEXPORT void JNICALL cpsNativeOnRead(JNIEnv* env, jclass, jlong handle, jbyteArray data) {
    auto* self = findInstance(static_cast<std::int64_t>(handle));
    if (!self || !data) return;
    jsize n = env->GetArrayLength(data);
    if (n <= 0) return;
    jbyte* p = env->GetByteArrayElements(data, nullptr);
    if (p) {
        self->handleData(reinterpret_cast<const std::uint8_t*>(p), static_cast<std::size_t>(n));
        env->ReleaseByteArrayElements(data, p, JNI_ABORT);
    }
}

JNIEXPORT void JNICALL cpsNativeOnError(JNIEnv*, jclass, jlong handle, jint code) {
    auto* self = findInstance(static_cast<std::int64_t>(handle));
    if (!self) return;
    SerialError e = (code == 0) ? SerialError::ReadError : SerialError::ResourceError;
    if (self->onError) self->onError(e);
}

SerialError loadBridge(JNIEnv* env) {
    if (!env || !g_context) { CPS_LOGE("loadBridge: no env/context"); return SerialError::UnsupportedOperationError; }
    if (g_bridgeClass) return SerialError::NoError;

    // codeCacheDir absolute path
    jclass ctxClass = env->GetObjectClass(g_context);
    jmethodID midGetCache = env->GetMethodID(ctxClass, "getCodeCacheDir", "()Ljava/io/File;");
    jobject cacheDir = midGetCache ? env->CallObjectMethod(g_context, midGetCache) : nullptr;
    env->DeleteLocalRef(ctxClass);
    if (env->ExceptionCheck()) { env->ExceptionClear(); CPS_LOGE("loadBridge: getCodeCacheDir failed"); return SerialError::UnknownError; }

    jclass fileClass = env->FindClass("java/io/File");
    jmethodID midGetPath = env->GetMethodID(fileClass, "getAbsolutePath", "()Ljava/lang/String;");
    jstring jCachePath = cacheDir ? (jstring) env->CallObjectMethod(cacheDir, midGetPath) : nullptr;
    env->DeleteLocalRef(fileClass);
    env->DeleteLocalRef(cacheDir);
    if (!jCachePath) { CPS_LOGE("loadBridge: cache dir path failed"); return SerialError::UnknownError; }

    const char* cp = env->GetStringUTFChars(jCachePath, nullptr);
    std::string dir = std::string(cp) + "/cps";
    std::string dexPath = dir + "/cps.dex";
    env->ReleaseStringUTFChars(jCachePath, cp);
    env->DeleteLocalRef(jCachePath);

    ensureDir(dir);
    std::remove(dexPath.c_str()); // drop any stale read-only dex so we can rewrite it
    {
        std::ofstream f(dexPath, std::ios::binary | std::ios::trunc);
        if (!f) { CPS_LOGE("loadBridge: cannot write %s", dexPath.c_str()); return SerialError::ResourceError; }
        f.write(reinterpret_cast<const char*>(cps_classes_dex), cps_classes_dex_len);
        if (!f) { CPS_LOGE("loadBridge: write failed %s", dexPath.c_str()); return SerialError::ResourceError; }
    }
    // Android 10+ refuses to load a writable dex ("Attempt to load writable dex
    // file"); make it read-only so DexClassLoader accepts it.
    ::chmod(dexPath.c_str(), 0444);
    CPS_LOGI("loadBridge: wrote dex (%lu bytes) to %s", (unsigned long)cps_classes_dex_len, dexPath.c_str());

    // parent classloader = context class' loader
    jclass classClass = env->FindClass("java/lang/Class");
    jmethodID midGetCl = env->GetMethodID(classClass, "getClassLoader", "()Ljava/lang/ClassLoader;");
    jobject parentLoader = env->CallObjectMethod(env->GetObjectClass(g_context), midGetCl);
    env->DeleteLocalRef(classClass);

    jclass dexCls = env->FindClass("dalvik/system/DexClassLoader");
    jmethodID ctor = env->GetMethodID(dexCls, "<init>",
        "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/ClassLoader;)V");
    jstring jDexPath = env->NewStringUTF(dexPath.c_str());
    jobject loader = env->NewObject(dexCls, ctor, jDexPath, nullptr, nullptr, parentLoader);
    env->DeleteLocalRef(jDexPath);
    env->DeleteLocalRef(parentLoader);
    env->DeleteLocalRef(dexCls);
    if (env->ExceptionCheck() || !loader) { env->ExceptionClear(); CPS_LOGE("loadBridge: DexClassLoader failed"); return SerialError::UnknownError; }

    jmethodID midLoad = env->GetMethodID(env->GetObjectClass(loader), "loadClass",
                                         "(Ljava/lang/String;)Ljava/lang/Class;");
    jstring jName = env->NewStringUTF("com.cps.android.CpsUsbSerial");
    jclass bridge = (jclass) env->CallObjectMethod(loader, midLoad, jName);
    env->DeleteLocalRef(jName);
    env->DeleteLocalRef(loader);
    if (env->ExceptionCheck() || !bridge) { env->ExceptionClear(); CPS_LOGE("loadBridge: loadClass com.cps.android.CpsUsbSerial failed"); return SerialError::UnknownError; }

    g_bridgeClass = (jclass) env->NewGlobalRef(bridge);
    env->DeleteLocalRef(bridge);

    g_midEnumerate = env->GetStaticMethodID(g_bridgeClass, "enumerate", "()[Lcom/cps/android/CpsPortInfo;");
    g_midOpen      = env->GetStaticMethodID(g_bridgeClass, "open", "(JLjava/lang/String;IIIII)Z");
    g_midWrite     = env->GetStaticMethodID(g_bridgeClass, "write", "(J[B)I");
    g_midClose     = env->GetStaticMethodID(g_bridgeClass, "close", "(J)V");

    JNINativeMethod methods[] = {
        { "cpsNativeOnRead",  "(J[B)V", (void*) &cpsNativeOnRead },
        { "cpsNativeOnError", "(JI)V",  (void*) &cpsNativeOnError },
    };
    env->RegisterNatives(g_bridgeClass, methods, 2);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }

    // Hand the application Context to the Java bridge.
    jmethodID midSetCtx = env->GetStaticMethodID(g_bridgeClass, "setContext",
                                                 "(Landroid/content/Context;)V");
    if (midSetCtx && g_context) {
        env->CallStaticVoidMethod(g_bridgeClass, midSetCtx, g_context);
        if (env->ExceptionCheck()) env->ExceptionClear();
    }

    CPS_LOGI("loadBridge: ready (bridge=%p enumerate=%p open=%p)", (void*)g_bridgeClass, (void*)g_midEnumerate, (void*)g_midOpen);
    return SerialError::NoError;
}

} // namespace

// ---- module init ----------------------------------------------------------

SerialError androidInit(void* java_vm, void* context) {
    CPS_LOGI("androidInit: java_vm=%p context=%p g_vm=%p", java_vm, context, (void*)g_vm);
    if (java_vm) g_vm = static_cast<JavaVM*>(java_vm);
    if (!g_vm) { CPS_LOGE("androidInit: no JavaVM"); return SerialError::UnknownError; }
    if (context) {
        JniThread t(g_vm);
        if (!t.ok) { CPS_LOGE("androidInit: thread attach failed"); return SerialError::UnknownError; }
        if (g_context) t.env->DeleteGlobalRef(g_context);
        g_context = t.env->NewGlobalRef(static_cast<jobject>(context));
        SerialError e = loadBridge(t.env);
        if (t.env->ExceptionCheck()) { t.env->ExceptionClear(); }
        CPS_LOGI("androidInit: loadBridge -> %d  (bridge=%p)", (int)e, (void*)g_bridgeClass);
        if (t.attached) g_vm->DetachCurrentThread();
        return e;
    }
    return SerialError::NoError;
}

// ---- AndroidBackend -------------------------------------------------------

AndroidBackend::AndroidBackend() = default;
AndroidBackend::~AndroidBackend() { close(); }

void AndroidBackend::registerHandle()   { registerInstance(reinterpret_cast<std::int64_t>(this), this); }
void AndroidBackend::unregisterHandle() { unregisterInstance(reinterpret_cast<std::int64_t>(this)); }

bool AndroidBackend::open(const std::string& name, OpenMode) {
    if (!g_bridgeClass) { error_.store(SerialError::UnsupportedOperationError); return false; }
    JniThread t(g_vm);
    if (!t.ok) { error_.store(SerialError::UnknownError); return false; }

    jstring jname = t.env->NewStringUTF(name.c_str());
    jboolean ok = t.env->CallStaticBooleanMethod(g_bridgeClass, g_midOpen,
        static_cast<jlong>(reinterpret_cast<std::int64_t>(this)),
        jname,
        static_cast<int>(baud_),
        static_cast<int>(dataBits_),
        static_cast<int>(parity_),
        static_cast<int>(stopBits_),
        static_cast<int>(flow_));
    t.env->DeleteLocalRef(jname);
    if (t.env->ExceptionCheck()) { t.env->ExceptionClear(); ok = JNI_FALSE; }

    if (ok) {
        registerHandle();
        open_.store(true);
        error_.store(SerialError::NoError);
        return true;
    }
    error_.store(SerialError::OpenError);
    return false;
}

void AndroidBackend::close() {
    if (!open_.exchange(false)) return;
    unregisterHandle();
    if (g_bridgeClass && g_midClose) {
        JniThread t(g_vm);
        if (t.ok) {
            t.env->CallStaticVoidMethod(g_bridgeClass, g_midClose,
                static_cast<jlong>(reinterpret_cast<std::int64_t>(this)));
            if (t.env->ExceptionCheck()) t.env->ExceptionClear();
        }
    }
    std::lock_guard<std::mutex> lk(bufMx_);
    readBuffer_.clear();
}

bool AndroidBackend::isOpen() const { return open_.load(); }

bool AndroidBackend::setBaudRate(std::int32_t r) { baud_ = r; return true; }
bool AndroidBackend::setDataBits(DataBits b)     { dataBits_ = b; return true; }
bool AndroidBackend::setParity(Parity p)         { parity_ = p; return true; }
bool AndroidBackend::setStopBits(StopBits s)     { stopBits_ = s; return true; }
bool AndroidBackend::setFlowControl(FlowControl f){ flow_ = f; return true; }

std::int64_t AndroidBackend::write(const void* data, std::size_t size) {
    if (!open_.load()) { error_.store(SerialError::NotOpenError); return -1; }
    if (!g_bridgeClass || !g_midWrite) { error_.store(SerialError::UnsupportedOperationError); return -1; }
    JniThread t(g_vm);
    if (!t.ok) { error_.store(SerialError::UnknownError); return -1; }

    jbyteArray arr = t.env->NewByteArray(static_cast<jsize>(size));
    if (!arr) return -1;
    t.env->SetByteArrayRegion(arr, 0, static_cast<jsize>(size),
                              static_cast<const jbyte*>(data));
    jint written = t.env->CallStaticIntMethod(g_bridgeClass, g_midWrite,
        static_cast<jlong>(reinterpret_cast<std::int64_t>(this)), arr);
    t.env->DeleteLocalRef(arr);
    if (t.env->ExceptionCheck()) { t.env->ExceptionClear(); error_.store(SerialError::WriteError); return -1; }
    return static_cast<std::int64_t>(written);
}

std::int64_t AndroidBackend::read(void* buf, std::size_t max) {
    std::lock_guard<std::mutex> lk(bufMx_);
    return static_cast<std::int64_t>(readBuffer_.pop(static_cast<std::uint8_t*>(buf), max));
}
std::int64_t AndroidBackend::bytesAvailable() const {
    std::lock_guard<std::mutex> lk(bufMx_);
    return static_cast<std::int64_t>(readBuffer_.size());
}
std::int64_t AndroidBackend::bytesToWrite() const { return 0; }
bool AndroidBackend::flush() { return true; }
bool AndroidBackend::clear(Directions) {
    std::lock_guard<std::mutex> lk(bufMx_);
    readBuffer_.clear();
    return true;
}
SerialError AndroidBackend::lastError() const { return error_.load(); }
void AndroidBackend::clearError() { error_.store(SerialError::NoError); }

void AndroidBackend::handleData(const std::uint8_t* data, std::size_t n) {
    {
        std::lock_guard<std::mutex> lk(bufMx_);
        readBuffer_.push(data, n);
    }
    if (onReadyRead) onReadyRead();
}

// ---- enumeration (Android) ------------------------------------------------

std::vector<RawPortInfo> enumeratePorts() {
    std::vector<RawPortInfo> out;
    if (!g_bridgeClass || !g_midEnumerate) return out;
    JniThread t(g_vm);
    if (!t.ok) return out;

    jobjectArray arr = static_cast<jobjectArray>(
        t.env->CallStaticObjectMethod(g_bridgeClass, g_midEnumerate));
    if (t.env->ExceptionCheck()) { t.env->ExceptionClear(); return out; }
    if (!arr) return out;

    jsize n = t.env->GetArrayLength(arr);
    for (jsize i = 0; i < n; ++i) {
        jobject info = t.env->GetObjectArrayElement(arr, i);
        if (t.env->ExceptionCheck()) { t.env->ExceptionClear(); if (info) t.env->DeleteLocalRef(info); continue; }
        if (!info) continue;

        // CpsPortInfo is loaded by the DexClassLoader, NOT the system classloader, so
        // FindClass() can't see it (ClassNotFoundException). Get the class from the
        // object itself instead.
        jclass infoCls = t.env->GetObjectClass(info);

        RawPortInfo r;
        auto getStr = [&](const char* field) -> std::string {
            jfieldID fid = t.env->GetFieldID(infoCls, field, "Ljava/lang/String;");
            if (!fid) { if (t.env->ExceptionCheck()) t.env->ExceptionClear(); return {}; }
            jstring s = static_cast<jstring>(t.env->GetObjectField(info, fid));
            if (!s) return {};
            const char* cs = t.env->GetStringUTFChars(s, nullptr);
            std::string rs(cs ? cs : "");
            if (cs) t.env->ReleaseStringUTFChars(s, cs);
            t.env->DeleteLocalRef(s);
            return rs;
        };
        r.portName       = getStr("name");
        r.description    = getStr("description");
        r.manufacturer   = getStr("manufacturer");
        r.serialNumber   = getStr("serialNumber");
        r.systemLocation = getStr("systemLocation");
        jfieldID fvid = t.env->GetFieldID(infoCls, "vid", "I");
        jfieldID fpid = t.env->GetFieldID(infoCls, "pid", "I");
        if (t.env->ExceptionCheck()) t.env->ExceptionClear();
        if (fvid && fpid) {
            r.vendorId  = static_cast<std::uint16_t>(t.env->GetIntField(info, fvid));
            r.productId = static_cast<std::uint16_t>(t.env->GetIntField(info, fpid));
            r.hasUsbIds = (r.vendorId != 0 && r.productId != 0);
        }
        t.env->DeleteLocalRef(infoCls);
        t.env->DeleteLocalRef(info);
        out.push_back(std::move(r));
    }
    t.env->DeleteLocalRef(arr);
    return out;
}

#else  // !__ANDROID__ : stubs so the file compiles anywhere (not built on desktop)

SerialError androidInit(void*, void*) { return SerialError::UnsupportedOperationError; }

AndroidBackend::AndroidBackend() = default;
AndroidBackend::~AndroidBackend() = default;
bool AndroidBackend::open(const std::string&, OpenMode) { return false; }
void AndroidBackend::close() {}
bool AndroidBackend::isOpen() const { return false; }
bool AndroidBackend::setBaudRate(std::int32_t) { return false; }
bool AndroidBackend::setDataBits(DataBits) { return false; }
bool AndroidBackend::setParity(Parity) { return false; }
bool AndroidBackend::setStopBits(StopBits) { return false; }
bool AndroidBackend::setFlowControl(FlowControl) { return false; }
std::int64_t AndroidBackend::write(const void*, std::size_t) { return -1; }
std::int64_t AndroidBackend::read(void*, std::size_t) { return 0; }
std::int64_t AndroidBackend::bytesAvailable() const { return 0; }
std::int64_t AndroidBackend::bytesToWrite() const { return 0; }
bool AndroidBackend::flush() { return false; }
bool AndroidBackend::clear(Directions) { return false; }
SerialError AndroidBackend::lastError() const { return SerialError::UnsupportedOperationError; }
void AndroidBackend::clearError() {}
void AndroidBackend::handleData(const std::uint8_t*, std::size_t) {}
void AndroidBackend::registerHandle() {}
void AndroidBackend::unregisterHandle() {}
std::vector<RawPortInfo> enumeratePorts() { return {}; }

#endif // __ANDROID__

} // namespace detail
} // namespace cps

#ifdef __ANDROID__
extern "C" JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
    cps::detail::g_vm = vm;
    return JNI_VERSION_1_6;
}
#endif
