# Reads a binary file and emits a .cpp with a const unsigned char[] of its bytes.
# Usage: cmake -DCPS_DEX_IN=<path> -DCPS_CPP_OUT=<path> -P cps_dex_embed.cmake

if(NOT EXISTS "${CPS_DEX_IN}")
    message(FATAL_ERROR "cps_dex_embed: input not found: ${CPS_DEX_IN}")
endif()

file(READ "${CPS_DEX_IN}" _hex HEX)

# Split hex string into "0xNN," pairs, wrapped ~16 per line for readability.
string(REGEX REPLACE "(............................)" "\\1\n" _chunked "${_hex}")
string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " _bytes "${_chunked}")

file(WRITE "${CPS_CPP_OUT}"
"/* Auto-generated by cps_dex_embed.cmake - do not edit. */\n"
"extern \"C\" const unsigned char cps_classes_dex[] = {\n"
"${_bytes}\n"
"};\n"
"extern \"C\" const unsigned long cps_classes_dex_len = sizeof(cps_classes_dex);\n")
